project:
  type: website
  output-dir: docs

website:
  title: "proj"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

